# Generated by Django 5.0.4 on 2024-04-19 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postMedia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmedia',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
