# Generated by Django 5.0.4 on 2024-04-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
    ]
